version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10.6-management-alpine
    hostname: my-rabbitmq
    volumes:
      - './rabbitmq:/var/lib/rabbitmq/mnesia'
    ports:
      - 5672:5672
      - 15672:15672
    
